### ISSUE TITLE
Testing for any issues!

### ISSUE THREAD

**Issue by palashmon** [palashmon/car-names#12]
This is a task specifically for new contributors.

**Task:**  
- Test this project in different ways as possible, to find if it breaks in any scenario.
- Or if the error could have been handled in a better way.

**Steps:**
- Fork this repo.
- Get the project running locally
- Leave a message on this task if you'd like to work on
- Submit a pull request

Let me know if you are facing any issues running this project locally.

Regards!

**Comment by galagarza89** [comment]
I would like to test this project! Thanks!

**Comment by palashmon** [comment]
Sure. You can go ahead and start testing.

Regards!
